function rollD()
{
   var player1 = Math.ceil(Math.random() *6);
    //generates a random number between 1 and 6
    var player2 = Math.ceil(Math.random() *6);





  var dice1image = "dice1_image.png";  
  var dice2image = "dice2_image.png";
  var dice3image = "dice3_image.png";
  var dice4image = "dice4_image.png";
  var dice5image = "dice5_image.png";
  var dice6image = "dice6_image.png";
player1 = 1;
 if(player1  == 1)
(
    
document.getElementById("player1img").src = dice1image;
     
)
else if (player1)
 }